version: '2.4'

services:
  backend:
    restart: always
    hostname: gpu
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./app:/app/:delegated
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    build:
      context: ./
      dockerfile: Dockerfile-gpu
